// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Source: C:/Users/brand/OneDrive/Desktop/NCAA Statistics (1).xlsx
// Regenerate via: python scripts/build_conferences.py [xlsx-path]
//
// This file ships the canonical school -> conference table for D-I softball.
// It is the source of truth for any place the app displays a conference label.
//
// 308 NCAA Org strings preserve the spreadsheet's exact spelling, including
// backtick-as-apostrophe (Saint Mary`s) and abbreviated state names (St., Mich.,
// Conn.). The matcher in lookupConference normalizes all of those at runtime.

// NCAA Org -> conference (verbatim from the spreadsheet).
export const NCAA_TEAM_CONFERENCES = Object.freeze({
  'A&M-Corpus Christi': 'Southland',
  'Abilene Christian': 'WAC',
  'Akron': 'MAC',
  'Alabama': 'SEC',
  'Alabama A&M': 'SWAC',
  'Alabama St.': 'SWAC',
  'Alcorn': 'SWAC',
  'App State': 'Sun Belt',
  'Arizona': 'Big 12',
  'Arizona St.': 'Big 12',
  'Ark.-Pine Bluff': 'SWAC',
  'Arkansas': 'SEC',
  'Army West Point': 'Patriot',
  'Auburn': 'SEC',
  'Austin Peay': 'ASUN',
  'Ball St.': 'MAC',
  'Baylor': 'Big 12',
  'Bellarmine': 'ASUN',
  'Belmont': 'MVC',
  'Bethune-Cookman': 'SWAC',
  'Binghamton': 'America East',
  'Boise St.': 'Mountain West',
  'Boston College': 'ACC',
  'Boston U.': 'Patriot',
  'Bowling Green': 'MAC',
  'Bradley': 'MVC',
  'Brown': 'Ivy League',
  'Bryant': 'America East',
  'Bucknell': 'Patriot',
  'Buffalo': 'MAC',
  'Butler': 'Big East',
  'BYU': 'Big 12',
  'Cal Poly': 'Big West',
  'Cal St. Fullerton': 'Big West',
  'California': 'ACC',
  'California Baptist': 'WAC',
  'Campbell': 'CAA',
  'Canisius': 'MAAC',
  'Central Ark.': 'ASUN',
  'Central Conn. St.': 'NEC',
  'Central Mich.': 'MAC',
  'Charleston So.': 'Big South',
  'Charlotte': 'American',
  'Chattanooga': 'SoCon',
  'Clemson': 'ACC',
  'Coastal Carolina': 'Sun Belt',
  'Col. of Charleston': 'CAA',
  'Colgate': 'Patriot',
  'Colorado St.': 'Mountain West',
  'Columbia': 'Ivy League',
  'Coppin St.': 'MEAC',
  'Cornell': 'Ivy League',
  'Creighton': 'Big East',
  'CSU Bakersfield': 'Big West',
  'CSUN': 'Big West',
  'Dartmouth': 'Ivy League',
  'Dayton': 'Atlantic 10',
  'Delaware': 'CUSA',
  'Delaware St.': 'MEAC',
  'DePaul': 'Big East',
  'Detroit Mercy': 'Horizon',
  'Drake': 'MVC',
  'Drexel': 'CAA',
  'Duke': 'ACC',
  'East Carolina': 'American',
  'East Texas A&M': 'Southland',
  'Eastern Ill.': 'OVC',
  'Eastern Ky.': 'ASUN',
  'Elon': 'CAA',
  'ETSU': 'SoCon',
  'Evansville': 'MVC',
  'Fairfield': 'MAAC',
  'FDU': 'NEC',
  'FGCU': 'ASUN',
  'FIU': 'CUSA',
  'Fla. Atlantic': 'American',
  'Florida': 'SEC',
  'Florida A&M': 'SWAC',
  'Florida St.': 'ACC',
  'Fordham': 'Atlantic 10',
  'Fresno St.': 'Mountain West',
  'Furman': 'SoCon',
  'Ga. Southern': 'Sun Belt',
  'Gardner-Webb': 'Big South',
  'George Mason': 'Atlantic 10',
  'George Washington': 'Atlantic 10',
  'Georgetown': 'Big East',
  'Georgia': 'SEC',
  'Georgia St.': 'Sun Belt',
  'Georgia Tech': 'ACC',
  'Grambling': 'SWAC',
  'Grand Canyon': 'Mountain West',
  'Green Bay': 'Horizon',
  'Hampton': 'CAA',
  'Harvard': 'Ivy League',
  'Hawaii': 'Big West',
  'Hofstra': 'CAA',
  'Holy Cross': 'Patriot',
  'Houston': 'Big 12',
  'Houston Christian': 'Southland',
  'Howard': 'MEAC',
  'Idaho St.': 'Big Sky',
  'Illinois': 'Big Ten',
  'Illinois St.': 'MVC',
  'Indiana': 'Big Ten',
  'Indiana St.': 'MVC',
  'Iona': 'MAAC',
  'Iowa': 'Big Ten',
  'Iowa St.': 'Big 12',
  'IU Indy': 'Horizon',
  'Jackson St.': 'SWAC',
  'Jacksonville': 'ASUN',
  'Jacksonville St.': 'CUSA',
  'James Madison': 'Sun Belt',
  'Kansas': 'Big 12',
  'Kansas City': 'Summit League',
  'Kennesaw St.': 'CUSA',
  'Kent St.': 'MAC',
  'Kentucky': 'SEC',
  'Lafayette': 'Patriot',
  'Lamar University': 'Southland',
  'Le Moyne': 'NEC',
  'Lehigh': 'Patriot',
  'Liberty': 'CUSA',
  'Lindenwood': 'OVC',
  'Lipscomb': 'ASUN',
  'LIU': 'NEC',
  'LMU (CA)': 'WCC',
  'Long Beach St.': 'Big West',
  'Longwood': 'Big South',
  'Louisiana': 'Sun Belt',
  'Louisiana Tech': 'CUSA',
  'Louisville': 'ACC',
  'Loyola Chicago': 'Atlantic 10',
  'LSU': 'SEC',
  'Maine': 'America East',
  'Manhattan': 'MAAC',
  'Marist': 'MAAC',
  'Marshall': 'Sun Belt',
  'Maryland': 'Big Ten',
  'Massachusetts': 'MAC',
  'McNeese': 'Southland',
  'Memphis': 'American',
  'Mercer': 'SoCon',
  'Mercyhurst': 'NEC',
  'Merrimack': 'MAAC',
  'Miami (OH)': 'MAC',
  'Michigan': 'Big Ten',
  'Michigan St.': 'Big Ten',
  'Middle Tenn.': 'CUSA',
  'Minnesota': 'Big Ten',
  'Mississippi St.': 'SEC',
  'Mississippi Val.': 'SWAC',
  'Missouri': 'SEC',
  'Missouri St.': 'CUSA',
  'Monmouth': 'CAA',
  'Montana': 'Big Sky',
  'Morehead St.': 'OVC',
  'Morgan St.': 'MEAC',
  'Mount St. Mary\u0060s': 'MAAC',
  'Murray St.': 'MVC',
  'N.C. A&T': 'CAA',
  'N.C. Central': 'MEAC',
  'NC State': 'ACC',
  'Nebraska': 'Big Ten',
  'Nevada': 'Mountain West',
  'New Haven': 'NEC',
  'New Mexico': 'Mountain West',
  'New Mexico St.': 'CUSA',
  'Niagara': 'MAAC',
  'Nicholls': 'Southland',
  'NIU': 'MAC',
  'Norfolk St.': 'MEAC',
  'North Ala.': 'ASUN',
  'North Carolina': 'ACC',
  'North Dakota': 'Summit League',
  'North Dakota St.': 'Summit League',
  'North Florida': 'ASUN',
  'North Texas': 'American',
  'Northern Colo.': 'Big Sky',
  'Northern Ky.': 'Horizon',
  'Northwestern': 'Big Ten',
  'Northwestern St.': 'Southland',
  'Notre Dame': 'ACC',
  'Oakland': 'Horizon',
  'Ohio': 'MAC',
  'Ohio St.': 'Big Ten',
  'Oklahoma': 'SEC',
  'Oklahoma St.': 'Big 12',
  'Ole Miss': 'SEC',
  'Omaha': 'Summit League',
  'Oregon': 'Big Ten',
  'Oregon St.': 'WCC',
  'Pacific': 'WCC',
  'Penn': 'Ivy League',
  'Penn St.': 'Big Ten',
  'Pittsburgh': 'ACC',
  'Portland St.': 'Big Sky',
  'Prairie View': 'SWAC',
  'Presbyterian': 'Big South',
  'Princeton': 'Ivy League',
  'Providence': 'Big East',
  'Purdue': 'Big Ten',
  'Queens (NC)': 'ASUN',
  'Quinnipiac': 'MAAC',
  'Radford': 'Big South',
  'Rhode Island': 'Atlantic 10',
  'Rider': 'MAAC',
  'Robert Morris': 'Horizon',
  'Rutgers': 'Big Ten',
  'Sacramento St.': 'Big Sky',
  'Sacred Heart': 'MAAC',
  'Saint Francis': 'NEC',
  'Saint Joseph\u0060s': 'Atlantic 10',
  'Saint Louis': 'Atlantic 10',
  'Saint Mary\u0060s (CA)': 'WCC',
  'Saint Peter\u0060s': 'MAAC',
  'Sam Houston': 'CUSA',
  'Samford': 'SoCon',
  'San Diego': 'WCC',
  'San Diego St.': 'Mountain West',
  'San Jose St.': 'Mountain West',
  'Santa Clara': 'WCC',
  'Seattle U': 'WCC',
  'Seton Hall': 'Big East',
  'SFA': 'Southland',
  'Siena': 'MAAC',
  'SIUE': 'OVC',
  'South Alabama': 'Sun Belt',
  'South Carolina': 'SEC',
  'South Carolina St.': 'MEAC',
  'South Dakota': 'Summit League',
  'South Dakota St.': 'Summit League',
  'South Fla.': 'American',
  'Southeast Mo. St.': 'OVC',
  'Southeastern La.': 'Southland',
  'Southern Ill.': 'MVC',
  'Southern Ind.': 'OVC',
  'Southern Miss.': 'Sun Belt',
  'Southern U.': 'SWAC',
  'Southern Utah': 'WAC',
  'St. Bonaventure': 'Atlantic 10',
  'St. John\u0060s (NY)': 'Big East',
  'St. Thomas (MN)': 'Summit League',
  'Stanford': 'ACC',
  'Stetson': 'ASUN',
  'Stonehill': 'NEC',
  'Stony Brook': 'CAA',
  'Syracuse': 'ACC',
  'Tarleton St.': 'WAC',
  'Tennessee': 'SEC',
  'Tennessee St.': 'OVC',
  'Tennessee Tech': 'OVC',
  'Texas': 'SEC',
  'Texas A&M': 'SEC',
  'Texas Southern': 'SWAC',
  'Texas St.': 'Sun Belt',
  'Texas Tech': 'Big 12',
  'Toledo': 'MAC',
  'Towson': 'CAA',
  'Troy': 'Sun Belt',
  'Tulsa': 'American',
  'UAB': 'American',
  'UAlbany': 'America East',
  'UC Davis': 'Big West',
  'UC Riverside': 'Big West',
  'UC San Diego': 'Big West',
  'UC Santa Barbara': 'Big West',
  'UCF': 'Big 12',
  'UCLA': 'Big Ten',
  'UConn': 'Big East',
  'UIC': 'MVC',
  'UIW': 'Southland',
  'ULM': 'Sun Belt',
  'UMass Lowell': 'America East',
  'UMBC': 'America East',
  'UMES': 'MEAC',
  'UNC Greensboro': 'SoCon',
  'UNCW': 'CAA',
  'UNI': 'MVC',
  'UNLV': 'Mountain West',
  'USC Upstate': 'Big South',
  'UT Arlington': 'WAC',
  'UT Martin': 'OVC',
  'Utah': 'Big 12',
  'Utah St.': 'Mountain West',
  'Utah Tech': 'WAC',
  'Utah Valley': 'WAC',
  'UTEP': 'CUSA',
  'UTSA': 'American',
  'Valparaiso': 'MVC',
  'Villanova': 'Big East',
  'Virginia': 'ACC',
  'Virginia Tech': 'ACC',
  'Wagner': 'NEC',
  'Washington': 'Big Ten',
  'Weber St.': 'Big Sky',
  'West Ga.': 'ASUN',
  'Western Caro.': 'SoCon',
  'Western Ill.': 'OVC',
  'Western Ky.': 'CUSA',
  'Western Mich.': 'MAC',
  'Wichita St.': 'American',
  'Winthrop': 'Big South',
  'Wisconsin': 'Big Ten',
  'Wofford': 'SoCon',
  'Yale': 'Ivy League',
  'Youngstown St.': 'Horizon',
});

// Tier set for the StandingsView 'Major Only' filter.
export const POWER_CONFERENCES = new Set(['SEC', 'ACC', 'Big 12', 'Big Ten']);

// All Division I softball conferences from the spreadsheet, ordered by
// member count (descending).
export const ALL_CONFERENCES = Object.freeze([
  { name: 'Big Ten', size: 17 },
  { name: 'SEC', size: 15 },
  { name: 'ACC', size: 15 },
  { name: 'MAAC', size: 13 },
  { name: 'MAC', size: 12 },
  { name: 'SWAC', size: 12 },
  { name: 'Sun Belt', size: 12 },
  { name: 'ASUN', size: 12 },
  { name: 'CUSA', size: 12 },
  { name: 'Big 12', size: 11 },
  { name: 'MVC', size: 11 },
  { name: 'CAA', size: 11 },
  { name: 'Southland', size: 10 },
  { name: 'Mountain West', size: 10 },
  { name: 'Big West', size: 10 },
  { name: 'American', size: 10 },
  { name: 'OVC', size: 10 },
  { name: 'Big East', size: 9 },
  { name: 'NEC', size: 9 },
  { name: 'Atlantic 10', size: 9 },
  { name: 'Ivy League', size: 8 },
  { name: 'SoCon', size: 8 },
  { name: 'MEAC', size: 8 },
  { name: 'WAC', size: 7 },
  { name: 'Patriot', size: 7 },
  { name: 'Big South', size: 7 },
  { name: 'Horizon', size: 7 },
  { name: 'Summit League', size: 7 },
  { name: 'WCC', size: 7 },
  { name: 'America East', size: 6 },
  { name: 'Big Sky', size: 6 },
]);

// NCAA abbreviates state names with periods. Expand them BEFORE the
// generic normalizer so 'San Jose St.' resolves to 'san jose state'.
// Order matters: longer patterns first to avoid prefix collisions.
const NCAA_ABBREV_EXPAND = [
  [/\bSt\./g, 'State'],
  [/\bConn\./g, 'Connecticut'],
  [/\bMich\./g, 'Michigan'],
  [/\bMass\./g, 'Massachusetts'],
  [/\bIll\./g, 'Illinois'],
  [/\bInd\./g, 'Indiana'],
  [/\bKy\./g, 'Kentucky'],
  [/\bColo\./g, 'Colorado'],
  [/\bMo\./g, 'Missouri'],
  [/\bGa\./g, 'Georgia'],
  [/\bFla\./g, 'Florida'],
  [/\bLa\./g, 'Louisiana'],
  [/\bAla\./g, 'Alabama'],
  [/\bAriz\./g, 'Arizona'],
  [/\bArk\./g, 'Arkansas'],
  [/\bTenn\./g, 'Tennessee'],
  [/\bCalif\./g, 'California'],
  [/\bCaro\./g, 'Carolina'],
  [/\bTex\./g, 'Texas'],
  [/\bMd\./g, 'Maryland'],
  [/\bN\.\s?C\./g, 'North Carolina'],
  [/\bN\.\s?D\./g, 'North Dakota'],
  [/\bN\.\s?M\./g, 'New Mexico'],
  [/\bN\.\s?Y\./g, 'New York'],
  [/\bN\.\s?J\./g, 'New Jersey'],
  [/\bS\.\s?C\./g, 'South Carolina'],
  [/\bS\.\s?D\./g, 'South Dakota'],
  [/\bMinn\./g, 'Minnesota'],
  [/\bWash\./g, 'Washington'],
  [/\bWis\./g, 'Wisconsin'],
  [/\bVa\./g, 'Virginia'],
  [/\bVt\./g, 'Vermont'],
  [/\bDel\./g, 'Delaware'],
  [/\bOkla\./g, 'Oklahoma'],
  [/\bMiss\./g, 'Mississippi'],
  [/\bNeb\./g, 'Nebraska'],
  [/\bMt\./g, 'Mount'],
  [/\bMont\./g, 'Montana'],
  [/\bCol\./g, 'College'],
  [/\bU\./g, 'University'],
  [/\bVal\./g, 'Valley'],
];

// Genuinely-different names where the NCAA spelling and the ESPN/common
// spelling diverge beyond what the abbreviation table can fix. Keys are
// the spreadsheet Org spelling (lowercased, backticks stripped). Values
// are what ESPN's team directory typically calls the same school.
const HARD_ALIASES = Object.freeze({
  'a&m-corpus christi': 'Texas A&M-Corpus Christi',
  'alcorn': 'Alcorn State',
  'ark.-pine bluff': 'Arkansas-Pine Bluff',
  'army west point': 'Army',
  'central ark.': 'Central Arkansas',
  'central conn. st.': 'Central Connecticut',
  'central mich.': 'Central Michigan',
  'col. of charleston': 'Charleston',
  'csu bakersfield': 'Cal State Bakersfield',
  'east texas a&m': 'East Texas A&M',
  'eastern ill.': 'Eastern Illinois',
  'eastern ky.': 'Eastern Kentucky',
  'fla. atlantic': 'Florida Atlantic',
  'hawaii': 'Hawai\'i',
  'lamar university': 'Lamar',
  'lmu (ca)': 'Loyola Marymount',
  'middle tenn.': 'Middle Tennessee',
  'mississippi val.': 'Mississippi Valley State',
  'n.c. a&t': 'North Carolina A&T',
  'n.c. central': 'North Carolina Central',
  'north ala.': 'North Alabama',
  'northern colo.': 'Northern Colorado',
  'northern ky.': 'Northern Kentucky',
  'queens (nc)': 'Queens',
  'saint josephs': 'Saint Joseph\'s',
  'saint marys (ca)': 'Saint Mary\'s',
  'saint peters': 'Saint Peter\'s',
  'san jose st.': 'San Jose State',
  'south fla.': 'South Florida',
  'southeast mo. st.': 'Southeast Missouri State',
  'southeastern la.': 'Southeastern Louisiana',
  'southern ill.': 'Southern Illinois',
  'southern ind.': 'Southern Indiana',
  'southern u.': 'Southern',
  'st. johns (ny)': 'St. John\'s',
  'st. thomas (mn)': 'St. Thomas',
  'tarleton st.': 'Tarleton State',
  'uc san diego': 'UC San Diego',
  'usc upstate': 'USC Upstate',
  'west ga.': 'West Georgia',
  'western caro.': 'Western Carolina',
  'western ill.': 'Western Illinois',
  'western mich.': 'Western Michigan',
});

// Reverse aliases: keys are the EXPANDED ESPN-style spelling, values are
// the spreadsheet's abbreviated Org. The index-builder also adds entries
// for each of these so callers passing ESPN's long form (e.g.
// 'Charleston Southern', 'IU Indianapolis') resolve to the right row.
const REVERSE_ALIASES = Object.freeze({
  'Cal': 'California',
  'Charleston Southern': 'Charleston So.',
  'East Tennessee State': 'ETSU',
  'Fairleigh Dickinson': 'FDU',
  'Florida Gulf Coast': 'FGCU',
  'Florida International': 'FIU',
  'IU Indianapolis': 'IU Indy',
  'Mount St. Mary\'s': 'Mount St. Mary\u0060s',
  'Pennsylvania': 'Penn',
  'Prairie View A&M': 'Prairie View',
  'SIU Edwardsville': 'SIUE',
});

function expandAbbrev(s) {
  let out = s;
  for (const [pat, repl] of NCAA_ABBREV_EXPAND) out = out.replace(pat, repl);
  return out;
}

function normalize(s) {
  if (!s) return '';
  return s
    .normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/`/g, '')
    .replace(/[^a-z0-9 ]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Build the runtime lookup index ONCE at module load. Each NCAA Org gets
// indexed under multiple normalized variants so callers can hit it with
// whichever team-name shape they happen to have (ESPN displayName, ESPN
// location, NCAA Org, henrygd school slug, etc.).
const lookupIndex = (() => {
  const idx = new Map();
  const add = (key, conf) => {
    const n = normalize(key);
    if (n && !idx.has(n)) idx.set(n, conf);
  };
  for (const [org, conf] of Object.entries(NCAA_TEAM_CONFERENCES)) {
    add(org, conf);
    add(expandAbbrev(org), conf);
    const aliasKey = org.toLowerCase().replace(/`/g, '');
    const aliased = HARD_ALIASES[aliasKey];
    if (aliased) add(aliased, conf);
  }
  // Reverse aliases: ESPN-style spelling -> abbreviated spreadsheet Org.
  // Look up the conf via the spreadsheet form, then index the ESPN form.
  for (const [espnName, org] of Object.entries(REVERSE_ALIASES)) {
    const conf = NCAA_TEAM_CONFERENCES[org];
    if (conf) add(espnName, conf);
  }
  return idx;
})();

// Look up the conference for any team-name spelling. Returns null if no
// D-I softball program matches.
//
// IMPORTANT: callers should pass a clean school name (e.g. 'Oklahoma',
// not 'Oklahoma Sooners'). This function does NOT do substring fallback
// because schools-named-after-other-schools (Loyola Maryland, Eastern
// Michigan, Northern Illinois, Charleston Southern, etc.) collide with
// shorter D-I program names and a substring matcher routes them to the
// wrong conference. ESPN's `team.location` field is always mascot-free,
// so prefer that over `team.displayName` when the caller has both.
export function lookupConference(name) {
  if (!name) return null;
  const n = normalize(name);
  if (lookupIndex.has(n)) return lookupIndex.get(n);
  const expanded = normalize(expandAbbrev(name));
  if (lookupIndex.has(expanded)) return lookupIndex.get(expanded);
  return null;
}
