/**
 * app/api/d1-stats/route.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Serves the weekly-fetched D1 softball statistics that live in data/json/.
 * Those files are generated by scripts/fetch_d1_stats.py every Friday night
 * and committed to the repo, so Vercel serves them as static data — zero
 * external API calls at runtime.
 *
 * Endpoints
 * ──────────
 * GET /api/d1-stats
 *   → { season, generatedAt, conferences: [{name, slug, sections:{batters,pitchers,fielding}}] }
 *
 * GET /api/d1-stats?conference=big-ten
 *   → { conference, sections: { batters: [...players], pitchers: [...], fielding: [...] } }
 *
 * GET /api/d1-stats?conference=big-ten&section=batters
 *   → { conference, section, season, fetchedAt, columns, count, players: [...] }
 *
 * GET /api/d1-stats?conference=big-ten&section=batters&search=Polar
 *   → same shape but players filtered by name/team substring (case-insensitive)
 *
 * GET /api/d1-stats?conference=big-ten&section=batters&sortBy=avg&sortDir=desc
 *   → same shape but players sorted by the given column key
 *
 * Cache
 * ─────
 * Responses are cached for 1 hour on Vercel's edge (s-maxage=3600).
 * The data only changes once a week so this is very conservative.
 */

import { promises as fs } from 'fs';
import path from 'path';

// Root of the JSON data directory — relative to the project root
const DATA_DIR = path.join(process.cwd(), 'data', 'json');

// Cache the index.json in module memory to avoid repeated disk reads
let _indexCache = null;
let _indexCacheTime = 0;
const INDEX_TTL_MS = 60 * 60 * 1000; // 1 hour

async function readIndex() {
    const now = Date.now();
    if (_indexCache && now - _indexCacheTime < INDEX_TTL_MS) {
          return _indexCache;
    }
    try {
          const raw = await fs.readFile(path.join(DATA_DIR, 'index.json'), 'utf8');
          _indexCache = JSON.parse(raw);
          _indexCacheTime = now;
          return _indexCache;
    } catch {
          return null;
    }
}

async function readSection(confSlug, section) {
    try {
          const filePath = path.join(DATA_DIR, confSlug, `${section}.json`);
          const raw = await fs.readFile(filePath, 'utf8');
          return JSON.parse(raw);
    } catch {
          return null;
    }
}

function jsonResponse(data, status = 200, cacheSeconds = 3600) {
    return new Response(JSON.stringify(data), {
          status,
          headers: {
                  'Content-Type': 'application/json',
                  'Cache-Control': `public, max-age=60, s-maxage=${cacheSeconds}, stale-while-revalidate=86400`,
          },
    });
}

function filterAndSort(players, search, sortBy, sortDir) {
    let result = players;

  // Full-text search across all string fields (name, team, etc.)
  if (search) {
        const q = search.toLowerCase();
        result = result.filter((p) =>
                Object.values(p).some(
                          (v) => typeof v === 'string' && v.toLowerCase().includes(q)
                        )
                                   );
  }

  // Sort by any column key
  if (sortBy) {
        const dir = sortDir === 'asc' ? 1 : -1;
        result = [...result].sort((a, b) => {
                const av = a[sortBy];
                const bv = b[sortBy];
                // Numeric sort if both values look like numbers
                                        const an = parseFloat(av);
                const bn = parseFloat(bv);
                if (!isNaN(an) && !isNaN(bn)) return (an - bn) * dir;
                // String sort fallback
                                        const as = String(av ?? '');
                const bs = String(bv ?? '');
                return as.localeCompare(bs) * dir;
        });
  }

  return result;
}

export const dynamic = 'force-dynamic';
export const revalidate = 3600; // ISR: revalidate once per hour

export async function GET(request) {
    const { searchParams } = new URL(request.url);
    const conference = searchParams.get('conference');
    const section    = searchParams.get('section');
    const search     = searchParams.get('search') || '';
    const sortBy     = searchParams.get('sortBy') || '';
    const sortDir    = searchParams.get('sortDir') || 'desc';

  try {
        // ── Index (no params) ────────────────────────────────────────────────────
      if (!conference) {
              const index = await readIndex();
              if (!index) {
                        return jsonResponse(
                          {
                                        error: 'Stats data not yet available. The weekly job runs every Friday night.',
                                        hint: 'Trigger the workflow manually from the Actions tab to generate data immediately.',
                          },
                                    404
                                  );
              }
              return jsonResponse(index);
      }

      // Validate conference slug — allow only safe path characters
      const safeConf = conference.replace(/[^a-z0-9-]/gi, '');
        if (!safeConf) {
                return jsonResponse({ error: 'Invalid conference slug.' }, 400);
        }

      // ── All sections for a conference ────────────────────────────────────────
      if (!section) {
              const SECTIONS = ['batters', 'pitchers', 'fielding'];
              const results = {};
              let found = false;

          for (const sec of SECTIONS) {
                    const data = await readSection(safeConf, sec);
                    if (data) {
                                found = true;
                                let players = data.players || [];
                                if (search || sortBy) {
                                              players = filterAndSort(players, search, sortBy, sortDir);
                                }
                                results[sec] = players;
                    } else {
                                results[sec] = [];
                    }
          }

          if (!found) {
                    return jsonResponse(
                      { error: `No data found for conference "${safeConf}". Check the conference slug.` },
                                404
                              );
          }

          return jsonResponse({
                    conference: safeConf,
                    season: (await readIndex())?.season,
                    sections: results,
          });
      }

      // ── Single section ───────────────────────────────────────────────────────
      const VALID_SECTIONS = ['batters', 'pitchers', 'fielding'];
        if (!VALID_SECTIONS.includes(section)) {
                return jsonResponse(
                  { error: `Invalid section "${section}". Use: batters, pitchers, or fielding.` },
                          400
                        );
        }

      const data = await readSection(safeConf, section);
        if (!data) {
                return jsonResponse(
                  { error: `No data for ${safeConf}/${section}. It may not be available for this conference.` },
                          404
                        );
        }

      let players = data.players || [];
        if (search || sortBy) {
                players = filterAndSort(players, search, sortBy, sortDir);
        }

      return jsonResponse({
              ...data,
              players,
              count: players.length,
      });

  } catch (err) {
        console.error('[d1-stats] Unhandled error:', err);
        return jsonResponse({ error: 'Internal server error', detail: err.message }, 500);
  }
}
